server:
  port: 8080

spring:
  application:
    name: OAUTH-SERVER
  #zipkin:
    #base-url: http://127.0.0.1:9411/
    
#Not required these config since we have moved Eureka server config to Cloud config server using github   
#eureka:
  #client:
    #register-with-eureka: true
    #fetch-registry: true
    #service-url:
      #defaultZone: http://localhost:8761/eureka/
  #instance:
    #hostname: localhost